game:
  type_: "connect_four"
  size: [6, 7]
  # type_: "tic_tac_toe"
  initial_state: ""

num_procs: 4

player_one:
  type_: "mcts"
  # model: "m1"
  params:
    seed: 87
    gamma: 1.0
    num_samples: 9216
    tree_policy:
      type_: "ucb1"
      C: 1.0
      # seed: 1
    final_policy:
      type_: "lcb"
      # seed: 1
    eval_func:
      type_: "random_rollout"
      # seed: 2

player_two:
  type_: "random"
  params:
    seed: 4

inference_servers: [
#   {
#     type_: "puct",
#     model_type: "CNN",
#     name: "m1"
#     ckpt_dir: "/Users/zaheen/projects/node_arena/python/checkpoints/",
#     batch_size: 32,
#     seed: 0,
#     model_hypers: []
#   },
#   # {
#   #   type_: "none2",
#   #   ckpt_dir: "some other path",
#   #   seed: 0,
#   #   model_hypers: [1, 2]
#   # }
]
